// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {NodeProp} from "@lezer/common"
const spec_identifier = {__proto__:null,component:6, val:28, true:36, false:36}
export const parser = LRParser.deserialize({
  version: 13,
  states: "(dOYQPOOQYQPOOO_QPO'#C^OOQO'#Cx'#CxOOQO-E6v-E6vOOQO'#C`'#C`OdQPO,58xOiQPO'#CcOqQPO1G.dOOQO,58},58}OvQPO,58}O!OQPO'#CgO!TQPO7+$OO!YQPO'#CyO!_QPO1G.iOOQO1G.i1G.iOOQO'#Cz'#CzO!gQPO,59RO_QPO'#CiO!oQPO<<GjOOQO,59e,59eOOQO-E6w-E6wOOQO7+$T7+$TOOQO-E6x-E6xOOQO1G.m1G.mO!tQQO,59TO!yQPO'#CpOOQOAN=UAN=UO#OQPO1G.oO#ZQQO'#DTOOQO'#Cq'#CqO#`QPO'#CqO#hQPO,59[OOQO'#DS'#DSO#mQPO7+$ZO#rQPO,59oOOQO'#C|'#C|O#`QPO,59]O#}QQO'#DVOOQO,59],59]OOQO1G.v1G.vOOQO<<Gu<<GuOOQO1G/Z1G/ZO$SQQO'#CuOOQO'#C{'#C{O$XQPO1G/[OOQO1G/[1G/[OOQO-E6z-E6zOOQO1G.w1G.wO$aQPO,59qO$fQPO,59aOOQO-E6y-E6yOOQO7+$v7+$vOOQO1G/]1G/]O#OQPO1G.{O$kQPO7+$gOOQO<<HR<<HR",
  stateData: "$s~OsOStOS~ORQO~OuTO~OUVO~OTXOuYO~OYZO~OT_OW]O~O^bO~OccO~OudO~OTfOW]O~OXhO^bO~OUjO~O_lO~OfmO~O`qOaqObqO~OgsO~OfmOkvO~OTxO~O[yO~OhzOj!OOuTO~Og!RO~O_!SO~Oj!UOuTO~Oj!VO~OY!WO~OX!YO~Ogu~",
  goto: "#yzPP{P!PPP!ZPPP!^P!aPPPPPP!e!hPPP!oPP!s!y#P#V#]PPPPP#c#i#n#sTROPQUQQibT{s}RWUR[WT`ZaRkcQpjTtouT|s}QPORSPQ^YRe^QaZRgaQ}sR!T}QuoR!PuQrlR!X!WVnjouVojouQwoR!Qu",
  nodeNames: "⚠ Script ComponentDeclaration component VariableName ) ( Parameters , } { ComponentStateDeclaration ; VariableDeclaration val Equals Number String Boolean Arrow ComponentTemplate Element ElementStartTag ElementIdentifier ElementSelfCloseEndTag ElementAttribute ElementEndTag ElementStartCloseTag",
  maxTerm: 41,
  nodeProps: [
    [NodeProp.openedBy, 5,"(",9,"{"],
    [NodeProp.closedBy, 6,")",10,"}"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "/h~RyXY#rYZ$gZ[#r]^$gpq#rrs$ltu%`wx&hxy'Vyz'[|}'a!O!P'f!P!Q(r!Q!R(}!R![)o!]!^,W!^!_,]!_!`,j!`!a,w!c!}%`#R#S%`#T#o%`#o#p,|#q#r-R$f$g#r$g#BY%`#BY#BZ-W#BZ$IS%`$IS$I_-W$I_$I|%`$I|$I}.x$I}$JO.x$JO$JT%`$JT$JU-W$JU$KV%`$KV$KW-W$KW&FU%`&FU&FV-W&FV?HT%`?HT?HU-W?HU~%`~#wYs~XY#rZ[#rpq#r$f$g#r#BY#BZ#r$IS$I_#r$JT$JU#r$KV$KW#r&FU&FV#r?HT?HU#r~$lOt~~$qUa~OY$lZr$lrs%Ts#O$l#O#P%Y#P~$l~%YOa~~%]PO~$lR%gVgQuPtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$g~%`Q&RVgQtu%|}!O%|!Q![%|!c!}%|#R#S%|#T#o%|$g~%|~&mUa~OY&hZw&hwx%Tx#O&h#O#P'P#P~&h~'SPO~&h~'[OU~~'aOT~~'fOW~~'iP!Q!['l~'qS`~!Q!['l!g!h'}#R#S'l#X#Y'}~(QS{|(^}!O(^!Q![(g#R#S(g~(aQ!Q![(g#R#S(g~(lQ`~!Q![(g#R#S(g~(uP!`!a(x~(}Oh~~)SX`~!O!P'l!Q![)o!g!h'}#R#S)o#U#V*]#X#Y'}#b#c*W#c#d*z#l#m+c~)tU`~!O!P'l!Q![)o!g!h'}#R#S)o#X#Y'}#b#c*W~*]O`~~*`R!Q!R*i!R!S*i#R#S*i~*nS`~!Q!R*i!R!S*i#R#S*i#b#c*W~*}Q!Q!Y+T#R#S+T~+YR`~!Q!Y+T#R#S+T#b#c*W~+fS!Q![+r!c!i+r#R#S+r#T#Z+r~+wT`~!Q![+r!c!i+r#R#S+r#T#Z+r#b#c*W~,]O[~~,bPf~!P!Q,e~,jOk~R,oP_Q!`!a,rP,wOcP~,|Oj~~-ROY~~-WOX~~-ags~gQuPXY#rZ[#rpq#rtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$f$g#r$g#BY%`#BY#BZ-W#BZ$IS%`$IS$I_-W$I_$JT%`$JT$JU-W$JU$KV%`$KV$KW-W$KW&FU%`&FU&FV-W&FV?HT%`?HT?HU-W?HU~%`~/RVt~gQuPtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$g~%`",
  tokenizers: [0, 1],
  topRules: {"Script":[0,1]},
  specialized: [{term: 37, get: value => spec_identifier[value] || -1}],
  tokenPrec: 170
})
