// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
const spec_identifier = {
  __proto__: null,
  component: 6,
  true: 24,
  false: 24,
  val: 38,
};
export const parser = LRParser.deserialize({
  version: 14,
  states:
    ")SOYQPOOQYQPOOO_QPO'#C^OOQO'#Cy'#CyOOQO-E6w-E6wOOQO'#C`'#C`OdQPO,58xOiQPO'#CcOqQPO1G.dOyQQO'#CdOOQO,58},58}O!OQPO,58}O!WQPO'#ClO!]QPO7+$OO!bQPO7+$OO!gQPO,59OOlQPO'#CzO!rQPO1G.iOOQO1G.i1G.iOOQO'#C{'#C{O!zQPO,59WO_QPO'#CnO#SQPO'#CqOOQO<<Gj<<GjO!]QPO<<GjOOQO'#DT'#DTOOQO1G.j1G.jOOQO,59f,59fOOQO-E6x-E6xOOQO7+$T7+$TOOQO-E6y-E6yOOQO1G.r1G.rO#XQQO,59YO#^QQO'#DUOOQO'#Cr'#CrO#cQPO'#CrO#kQPO,59]OOQOAN=UAN=UO!gQPO1G.tO#pQPO,59pOOQO'#C}'#C}O#cQPO,59^O#{QQO'#DWOOQO,59^,59^OOQO1G.w1G.wO$QQPO7+$`OOQO1G/[1G/[O$VQQO'#CvOOQO'#C|'#C|O$[QPO1G/]OOQO1G/]1G/]OOQO-E6{-E6{OOQO1G.x1G.xO$dQPO,59rOOQO<<Gz<<GzO$iQPO,59bOOQO-E6z-E6zOOQO7+$w7+$wOOQO1G/^1G/^O!gQPO1G.|O$nQPO7+$hOOQO<<HS<<HS",
  stateData:
    '$x~OtOSuOS~ORQO~OvTO~OUVO~OTYOvXO~O_[Od]O~OX_O~OTbO]`O~OceO~OUfO~OdhO~OYiOZiO[iO~OTmO]`O~O^oOceO~OgqO~OXvO~OhwO~OgqOlzO~OT|O~Oi!OOk!SOvTO~Oh!VO~Oa!WO~OX!XO~Ok!ZOvTO~Ok![O~O_!]O~O^!_O~Otuhv~',
  goto: '$W{PP|P!QPP![!_PPPPPPP!eP!hPP!l!rPPP!yPP!}#T#Z#a#gPPPPP#m#v#{$QTROPQUQQpeT!Pw!RRWUQZVRk`R^WTc[dQg]RuhQtfTxsyT!Qw!RQPORSPQaZRlaQd[RndQ!RwR!Y!RQysR!TyQj_Q}vR!^!]VrfsyVsfsyQ{sR!Uy',
  nodeNames:
    '⚠ Script ComponentDeclaration component VariableName ) ( ComponentProps ComponentPropDeclaration Equals Number String Boolean , } { ComponentStateDeclaration ; VariableDeclaration val Arrow ComponentTemplate Element ElementStartTag ElementIdentifier ElementSelfCloseEndTag ElementAttribute ElementEndTag ElementStartCloseTag',
  maxTerm: 42,
  nodeProps: [
    ['openedBy', 5, '(', 14, '{'],
    ['closedBy', 6, ')', 15, '}'],
  ],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData:
    "2l~R{XY#xYZ$mZ[#x]^$mpq#xrs$rtu&jwx([xy)}yz*S|}*X!O!P*^!P!Q+j!Q!R+u!R![,g!]!^/O!^!_/T!_!`/b!`!a/o!c!}&j#R#S&j#T#o&j#o#p/t#q#r/y$f$g#x$g#BY&j#BY#BZ0O#BZ$IS&j$IS$I_0O$I_$I|&j$I|$I}1v$I}$JO1v$JO$JT&j$JT$JU0O$JU$KV&j$KV$KW0O$KW&FU&j&FU&FV0O&FV;'S&j;'S;=`(U<%l?HT&j?HT?HU0O?HUO&j~#}Yt~XY#xZ[#xpq#x$f$g#x#BY#BZ#x$IS$I_#x$JT$JU#x$KV$KW#x&FU&FV#x?HT?HU#x~$rOu~~$wWZ~OY$rZr$rrs%as#O$r#O#P%f#P;'S$r;'S;=`&d<%lO$r~%fOZ~~%iRO;'S$r;'S;=`%r;=`O$r~%wXZ~OY$rZr$rrs%as#O$r#O#P%f#P;'S$r;'S;=`&d;=`<%l$r<%lO$r~&gP;=`<%l$rR&qXhQvPtu&j}!O'^!Q![&j!c!}&j#R#S&j#T#o&j$g;'S&j;'S;=`(U<%lO&jQ'cXhQtu'^}!O'^!Q!['^!c!}'^#R#S'^#T#o'^$g;'S'^;'S;=`(O<%lO'^Q(RP;=`<%l'^R(XP;=`<%l&j~(aWZ~OY([Zw([wx%ax#O([#O#P(y#P;'S([;'S;=`)w<%lO([~(|RO;'S([;'S;=`)V;=`O([~)[XZ~OY([Zw([wx%ax#O([#O#P(y#P;'S([;'S;=`)w;=`<%l([<%lO([~)zP;=`<%l([~*SOU~~*XOT~~*^O]~~*aP!Q![*d~*iSY~!Q![*d!g!h*u#R#S*d#X#Y*u~*xS{|+U}!O+U!Q![+_#R#S+_~+XQ!Q![+_#R#S+_~+dQY~!Q![+_#R#S+_~+mP!`!a+p~+uOi~~+zXY~!O!P*d!Q![,g!g!h*u#R#S,g#U#V-T#X#Y*u#b#c-O#c#d-r#l#m.Z~,lUY~!O!P*d!Q![,g!g!h*u#R#S,g#X#Y*u#b#c-O~-TOY~~-WR!Q!R-a!R!S-a#R#S-a~-fSY~!Q!R-a!R!S-a#R#S-a#b#c-O~-uQ!Q!Y-{#R#S-{~.QRY~!Q!Y-{#R#S-{#b#c-O~.^S!Q![.j!c!i.j#R#S.j#T#Z.j~.oTY~!Q![.j!c!i.j#R#S.j#T#Z.j#b#c-O~/TOa~~/YPg~!P!Q/]~/bOl~R/gPXQ!`!a/jP/oOdP~/tOk~~/yO_~~0OO^~~0Xit~hQvPXY#xZ[#xpq#xtu&j}!O'^!Q![&j!c!}&j#R#S&j#T#o&j$f$g#x$g#BY&j#BY#BZ0O#BZ$IS&j$IS$I_0O$I_$JT&j$JT$JU0O$JU$KV&j$KV$KW0O$KW&FU&j&FU&FV0O&FV;'S&j;'S;=`(U<%l?HT&j?HT?HU0O?HUO&j~2PXu~hQvPtu&j}!O'^!Q![&j!c!}&j#R#S&j#T#o&j$g;'S&j;'S;=`(U<%lO&j",
  tokenizers: [0, 1],
  topRules: { Script: [0, 1] },
  specialized: [{ term: 38, get: (value) => spec_identifier[value] || -1 }],
  tokenPrec: 173,
});
