// This file was generated by lezer-generator. You probably shouldn't edit it.
import { NodeProp } from '@lezer/common';
import { LRParser } from '@lezer/lr';
const spec_identifier = {
  __proto__: null,
  component: 6,
  true: 24,
  false: 24,
  val: 38,
};
export const parser = LRParser.deserialize({
  version: 13,
  states:
    ")SOYQPOOQYQPOOO_QPO'#C^OOQO'#Cy'#CyOOQO-E6w-E6wOOQO'#C`'#C`OdQPO,58xOiQPO'#CcOqQPO1G.dOyQQO'#CdOOQO,58},58}O!OQPO,58}O!WQPO'#ClO!]QPO7+$OO!bQPO7+$OO!gQPO,59OOlQPO'#CzO!rQPO1G.iOOQO1G.i1G.iOOQO'#C{'#C{O!zQPO,59WO_QPO'#CnO#SQPO'#CqOOQO<<Gj<<GjO!]QPO<<GjOOQO'#DT'#DTOOQO1G.j1G.jOOQO,59f,59fOOQO-E6x-E6xOOQO7+$T7+$TOOQO-E6y-E6yOOQO1G.r1G.rO#XQQO,59YO#^QQO'#DUOOQO'#Cr'#CrO#cQPO'#CrO#kQPO,59]OOQOAN=UAN=UO!gQPO1G.tO#pQPO,59pOOQO'#C}'#C}O#cQPO,59^O#{QQO'#DWOOQO,59^,59^OOQO1G.w1G.wO$QQPO7+$`OOQO1G/[1G/[O$VQQO'#CvOOQO'#C|'#C|O$[QPO1G/]OOQO1G/]1G/]OOQO-E6{-E6{OOQO1G.x1G.xO$dQPO,59rOOQO<<Gz<<GzO$iQPO,59bOOQO-E6z-E6zOOQO7+$w7+$wOOQO1G/^1G/^O!gQPO1G.|O$nQPO7+$hOOQO<<HS<<HS",
  stateData:
    '$v~OtOSuOS~ORQO~OvTO~OUVO~OTYOvXO~O_[Od]O~OX_O~OTbO]`O~OceO~OUfO~OdhO~OYiOZiO[iO~OTmO]`O~O^oOceO~OgqO~OXvO~OhwO~OgqOlzO~OT|O~Oi!OOk!SOvTO~Oh!VO~Oa!WO~OX!XO~Ok!ZOvTO~Ok![O~O_!]O~O^!_O~Ohv~',
  goto: '$W{PP|P!QPP![!_PPPPPPP!eP!hPP!l!rPPP!yPP!}#T#Z#a#gPPPPP#m#v#{$QTROPQUQQpeT!Pw!RRWUQZVRk`R^WTc[dQg]RuhQtfTxsyT!Qw!RQPORSPQaZRlaQd[RndQ!RwR!Y!RQysR!TyQj_Q}vR!^!]VrfsyVsfsyQ{sR!Uy',
  nodeNames:
    '⚠ Script ComponentDeclaration component VariableName ) ( ComponentProps ComponentPropDeclaration Equals Number String Boolean , } { ComponentStateDeclaration ; VariableDeclaration val Arrow ComponentTemplate Element ElementStartTag ElementIdentifier ElementSelfCloseEndTag ElementAttribute ElementEndTag ElementStartCloseTag',
  maxTerm: 42,
  nodeProps: [
    [NodeProp.openedBy, 5, '(', 14, '{'],
    [NodeProp.closedBy, 6, ')', 15, '}'],
  ],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData:
    "/h~RyXY#rYZ$gZ[#r]^$gpq#rrs$ltu%`wx&hxy'Vyz'[|}'a!O!P'f!P!Q(r!Q!R(}!R![)o!]!^,W!^!_,]!_!`,j!`!a,w!c!}%`#R#S%`#T#o%`#o#p,|#q#r-R$f$g#r$g#BY%`#BY#BZ-W#BZ$IS%`$IS$I_-W$I_$I|%`$I|$I}.x$I}$JO.x$JO$JT%`$JT$JU-W$JU$KV%`$KV$KW-W$KW&FU%`&FU&FV-W&FV?HT%`?HT?HU-W?HU~%`~#wYt~XY#rZ[#rpq#r$f$g#r#BY#BZ#r$IS$I_#r$JT$JU#r$KV$KW#r&FU&FV#r?HT?HU#r~$lOu~~$qUZ~OY$lZr$lrs%Ts#O$l#O#P%Y#P~$l~%YOZ~~%]PO~$lR%gVhQvPtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$g~%`Q&RVhQtu%|}!O%|!Q![%|!c!}%|#R#S%|#T#o%|$g~%|~&mUZ~OY&hZw&hwx%Tx#O&h#O#P'P#P~&h~'SPO~&h~'[OU~~'aOT~~'fO]~~'iP!Q!['l~'qSY~!Q!['l!g!h'}#R#S'l#X#Y'}~(QS{|(^}!O(^!Q![(g#R#S(g~(aQ!Q![(g#R#S(g~(lQY~!Q![(g#R#S(g~(uP!`!a(x~(}Oi~~)SXY~!O!P'l!Q![)o!g!h'}#R#S)o#U#V*]#X#Y'}#b#c*W#c#d*z#l#m+c~)tUY~!O!P'l!Q![)o!g!h'}#R#S)o#X#Y'}#b#c*W~*]OY~~*`R!Q!R*i!R!S*i#R#S*i~*nSY~!Q!R*i!R!S*i#R#S*i#b#c*W~*}Q!Q!Y+T#R#S+T~+YRY~!Q!Y+T#R#S+T#b#c*W~+fS!Q![+r!c!i+r#R#S+r#T#Z+r~+wTY~!Q![+r!c!i+r#R#S+r#T#Z+r#b#c*W~,]Oa~~,bPg~!P!Q,e~,jOl~R,oPXQ!`!a,rP,wOdP~,|Ok~~-RO_~~-WO^~~-agt~hQvPXY#rZ[#rpq#rtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$f$g#r$g#BY%`#BY#BZ-W#BZ$IS%`$IS$I_-W$I_$JT%`$JT$JU-W$JU$KV%`$KV$KW-W$KW&FU%`&FU&FV-W&FV?HT%`?HT?HU-W?HU~%`~/RVu~hQvPtu%`}!O%|!Q![%`!c!}%`#R#S%`#T#o%`$g~%`",
  tokenizers: [0, 1],
  topRules: { Script: [0, 1] },
  specialized: [{ term: 38, get: (value) => spec_identifier[value] || -1 }],
  tokenPrec: 173,
});
